In [6]:
import torch
x = torch.randn(2,4,4)

In [7]:
x

tensor([[[-0.3284, -0.1663,  0.0493, -1.2515],
         [ 0.3776, -1.2365,  0.7591,  0.1154],
         [-0.3662,  2.5799,  1.2822,  0.1995],
         [ 0.6959, -0.6822,  1.0911, -0.8555]],

        [[ 0.1446, -0.4933, -0.6923, -1.7867],
         [-0.6020, -0.5330,  3.2200, -0.2541],
         [-0.2562,  1.5477,  0.2958,  2.1809],
         [ 0.5333, -0.6100, -0.4629, -2.9514]]])

In [8]:
m,n = x.chunk(2, dim=1)

In [9]:
m

tensor([[[-0.3284, -0.1663,  0.0493, -1.2515],
         [ 0.3776, -1.2365,  0.7591,  0.1154]],

        [[ 0.1446, -0.4933, -0.6923, -1.7867],
         [-0.6020, -0.5330,  3.2200, -0.2541]]])

In [10]:
n

tensor([[[-0.3662,  2.5799,  1.2822,  0.1995],
         [ 0.6959, -0.6822,  1.0911, -0.8555]],

        [[-0.2562,  1.5477,  0.2958,  2.1809],
         [ 0.5333, -0.6100, -0.4629, -2.9514]]])

In [12]:
import torch
x = torch.randn(2,5,4)

In [13]:
x

tensor([[[ 1.5404,  0.0396, -0.6640,  0.3259],
         [ 0.6276,  0.3109, -0.0363,  0.1820],
         [-0.7374, -0.3713, -1.5113, -1.6359],
         [-0.7461,  0.0422, -0.3533, -0.2598],
         [ 0.5256, -0.7998, -0.0123,  1.2193]],

        [[-1.5294,  1.5355,  0.0555, -0.4233],
         [ 0.0091, -0.2733,  0.4021, -1.6416],
         [ 0.7250, -0.2265,  0.0979,  1.0784],
         [ 0.5349, -0.3170,  1.0217,  0.3276],
         [ 0.7120, -0.8174,  0.5537, -0.2914]]])

In [18]:
ord_token

tensor([[[ 0.3105],
         [ 0.2711],
         [-1.0640],
         [-0.3292],
         [ 0.2332]],

        [[-0.0904],
         [-0.3759],
         [ 0.4187],
         [ 0.3918],
         [ 0.0392]]])

In [17]:
ord_token = x.mean(dim=2).unsqueeze(-1)
ord_token.shape

torch.Size([2, 5, 1])

In [19]:
torch.matmul(ord_token.transpose(1,2), x).squeeze(2)

tensor([[[ 1.8011,  0.2912,  1.5054,  2.2609]],

        [[ 0.6759, -0.2872,  0.3068,  1.2239]]])

In [21]:
x.shape
x

tensor([[[ 1.5404,  0.0396, -0.6640,  0.3259],
         [ 0.6276,  0.3109, -0.0363,  0.1820],
         [-0.7374, -0.3713, -1.5113, -1.6359],
         [-0.7461,  0.0422, -0.3533, -0.2598],
         [ 0.5256, -0.7998, -0.0123,  1.2193]],

        [[-1.5294,  1.5355,  0.0555, -0.4233],
         [ 0.0091, -0.2733,  0.4021, -1.6416],
         [ 0.7250, -0.2265,  0.0979,  1.0784],
         [ 0.5349, -0.3170,  1.0217,  0.3276],
         [ 0.7120, -0.8174,  0.5537, -0.2914]]])

In [26]:
rearr = torch.tensor([[2, 0, 1, 3],[3, 0, 1, 2]])

In [33]:
rearr = rearr.unsqueeze(-1).expand(-1, -1, x.shape[1]).transpose(1,2)

In [34]:
rearr

tensor([[[2, 0, 1, 3],
         [2, 0, 1, 3],
         [2, 0, 1, 3],
         [2, 0, 1, 3],
         [2, 0, 1, 3]],

        [[3, 0, 1, 2],
         [3, 0, 1, 2],
         [3, 0, 1, 2],
         [3, 0, 1, 2],
         [3, 0, 1, 2]]])

In [36]:
x

tensor([[[ 1.5404,  0.0396, -0.6640,  0.3259],
         [ 0.6276,  0.3109, -0.0363,  0.1820],
         [-0.7374, -0.3713, -1.5113, -1.6359],
         [-0.7461,  0.0422, -0.3533, -0.2598],
         [ 0.5256, -0.7998, -0.0123,  1.2193]],

        [[-1.5294,  1.5355,  0.0555, -0.4233],
         [ 0.0091, -0.2733,  0.4021, -1.6416],
         [ 0.7250, -0.2265,  0.0979,  1.0784],
         [ 0.5349, -0.3170,  1.0217,  0.3276],
         [ 0.7120, -0.8174,  0.5537, -0.2914]]])

In [37]:
# Use torch.gather to reorder x based on rearr
output = torch.gather(x, dim=2, index=rearr)

print(output)

tensor([[[-0.6640,  1.5404,  0.0396,  0.3259],
         [-0.0363,  0.6276,  0.3109,  0.1820],
         [-1.5113, -0.7374, -0.3713, -1.6359],
         [-0.3533, -0.7461,  0.0422, -0.2598],
         [-0.0123,  0.5256, -0.7998,  1.2193]],

        [[-0.4233, -1.5294,  1.5355,  0.0555],
         [-1.6416,  0.0091, -0.2733,  0.4021],
         [ 1.0784,  0.7250, -0.2265,  0.0979],
         [ 0.3276,  0.5349, -0.3170,  1.0217],
         [-0.2914,  0.7120, -0.8174,  0.5537]]])


In [38]:
import torch

# Initialize an empty tensor to store the permutation matrices
perm_matrix = torch.zeros(2, 4, 4)

# Define arbitrary permutations for each matrix
perm1 = torch.tensor([[0, 1, 0, 0], 
                      [1, 0, 0, 0], 
                      [0, 0, 1, 0], 
                      [0, 0, 0, 1]])

perm2 = torch.tensor([[0, 0, 1, 0], 
                      [0, 1, 0, 0], 
                      [1, 0, 0, 0], 
                      [0, 0, 0, 1]])

# Store the permutation matrices
perm_matrix[0] = perm1
perm_matrix[1] = perm2

print(perm_matrix)


tensor([[[0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.]]])


In [39]:
print(x.shape) # [2, 5, 4]
print(perm_matrix.shape) # [2, 4, 4]

torch.Size([2, 5, 4])
torch.Size([2, 4, 4])


In [41]:
import torch

# Define x tensor
x = torch.tensor([[[-0.6640,  1.5404,  0.0396,  0.3259],
                   [-0.0363,  0.6276,  0.3109,  0.1820],
                   [-1.5113, -0.7374, -0.3713, -1.6359],
                   [-0.3533, -0.7461,  0.0422, -0.2598],
                   [-0.0123,  0.5256, -0.7998,  1.2193]],

                  [[-0.4233, -1.5294,  1.5355,  0.0555],
                   [-1.6416,  0.0091, -0.2733,  0.4021],
                   [ 1.0784,  0.7250, -0.2265,  0.0979],
                   [ 0.3276,  0.5349, -0.3170,  1.0217],
                   [-0.2914,  0.7120, -0.8174,  0.5537]]])

# Define the permutation matrix
perm_matrix = torch.tensor([[[0, 1, 0, 0], 
                             [1, 0, 0, 0], 
                             [0, 0, 1, 0], 
                             [0, 0, 0, 1]],

                            [[0, 0, 1, 0], 
                             [0, 1, 0, 0], 
                             [1, 0, 0, 0], 
                             [0, 0, 0, 1]]]).float()

# Perform einsum to reorder x based on perm_matrix
# Apply the permutation matrix to the last dimension (dim 4) of x
reordered_x = torch.einsum('bij,bjk->bik', x, perm_matrix)

print(reordered_x)


tensor([[[ 1.5404, -0.6640,  0.0396,  0.3259],
         [ 0.6276, -0.0363,  0.3109,  0.1820],
         [-0.7374, -1.5113, -0.3713, -1.6359],
         [-0.7461, -0.3533,  0.0422, -0.2598],
         [ 0.5256, -0.0123, -0.7998,  1.2193]],

        [[ 1.5355, -1.5294, -0.4233,  0.0555],
         [-0.2733,  0.0091, -1.6416,  0.4021],
         [-0.2265,  0.7250,  1.0784,  0.0979],
         [-0.3170,  0.5349,  0.3276,  1.0217],
         [-0.8174,  0.7120, -0.2914,  0.5537]]])
